<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>OnTheTrainDemoMod</AssemblyName>
    <RootNamespace>OnTheTrainDemoMod</RootNamespace>
    <OutputPath>bin\$(Configuration)</OutputPath>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Version>1.5.6</Version>
    <FileVersion>1.5.6.0</FileVersion>
    <AssemblyVersion>1.5.6.0</AssemblyVersion>
    <Company>DestinyWind</Company>
    <Authors>DestinyWind</Authors>
    <Copyright>DestinyWind</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="lang\zh-CN.json">
      <LogicalName>OnTheTrainDemoMod.lang.zh-CN.json</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="lang\en-US.json">
      <LogicalName>OnTheTrainDemoMod.lang.en-US.json</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MelonLoader">
      <HintPath>$(MSBuildThisFileDirectory)lib\MelonLoader.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(MSBuildThisFileDirectory)lib\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(MSBuildThisFileDirectory)lib\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(MSBuildThisFileDirectory)lib\UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(MSBuildThisFileDirectory)lib\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(MSBuildThisFileDirectory)lib\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(MSBuildThisFileDirectory)lib\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
